export enum Status {
    INIT,
    CONFIGQUESTIONNUMBER,
    CONFIGHARDNESS,
    CONFIGTIMEOUT,
    CONFIGKICKTOLERANCE,
    CONFIGCATHEGORYADD,
    CONFIGCATHEGORYREMOVE,
    CONFIGQUESTIONTYPE,
    PLAYING,
    PAUSED,
    STATS,
    PENDING
}
